---
#-- Install and configure MariaDB

- name: Install MariaDB packages
  package: name={{ item }} state=present
  with_items:
    - mariadb-server
    - mariadb

- name: Create data dir
  file: path=/mnt/data/mariadb state=directory recurse=yes owner=mysql group=mysql

- name: Copy config file
  copy: src=my.cnf dest=/etc/my.cnf owner=root group=root mode=0644

- name: Enable MariaDB
  service: name=mariadb enabled=yes

- name: Start MariaDB
  service: name=mariadb state=started

- name: See if the database is already secure
  command: mysql -u root -e "select now()"
  register: mysql_secure
  ignore_errors: True

- name: Lay down temporary script to secure maria
  template: src=secure_mariadb.sql.j2 dest=/tmp/secure_mariadb.sql owner=root group=root mode=0755
  when: mysql_secure.stderr.find("Access denied") == -1

- name: Secure mariadb
  shell: mysql -sfu root < "/tmp/secure_mariadb.sql"
  when: mysql_secure.stderr.find("Access denied") == -1

- name: Delete the temporary script
  file: path=/tmp/secure_mariadb.sql state=absent
