---
- name: install carbon-c-relay
  package: name=carbon-c-relay state=installed

- group: name=carbon

- user: name=carbon group=carbon

- name: configure carbon-c-relay
  template: src={{ graphite_role }}.conf.j2 dest=/etc/carbon-c-relay.conf
  notify:
    - restart carbon-c-relay

- name: enable service
  service: name=carbon-c-relay enabled=yes

- name: start service
  service: name=carbon-c-relay state=started
