---

- set_fact:
    mesos_ssl_basename: "{{ 'mesos-{{ region }}.{{ project }}' }}"
    mesos_certs_dir: /etc/pki/tls/certs/
    adminrouter_ssl_config_file: /opt/mesosphere/etc/adminrouter_ssl_nginx.conf

- set_fact:
    mesos_ssl_cert_key: "{{ lookup('vault',  '{{ mesos_ssl_basename }}.private', 'contents') | default(None) }}"
    mesos_ssl_cert: "{{ lookup('vault', '{{ mesos_ssl_basename }}.public', 'contents') | default(None) }}"
  no_log: True

- name: create ssl cert key
  template: src=cert_key.j2 dest={{ mesos_certs_dir }}/{{ mesos_ssl_basename }}.key mode=0700
  no_log: True

- name: create ssl cert
  template: src=cert.j2 dest={{ mesos_certs_dir }}/{{ mesos_ssl_basename }}.crt mode=0755

- name: find nginx.master.conf
  command: find /opt/mesosphere/packages/ -name nginx.master.conf
  register: nginx_find_result

- debug: var=nginx_find_result

- name: Fix 1.8.4 systemd unit file for dcos-adminrouter
  lineinfile: dest=/etc/systemd/system/dcos-adminrouter.service
              line="ExecReload=/usr/bin/kill -HUP $MAINPID"
              regexp="^ExecReload=/usr/bin/kill -HUP"
  notify:
    - systemctl reload

- name: Create the server block configuration for external dcos requests to adminrouter
  template: src=adminrouter_ssl_nginx.conf.j2 dest="{{ adminrouter_ssl_config_file }}"
  notify:
    - dcos-adminrouter reload

- name: Inject include statement to reference adminrouter_ssl_nginx.conf 
  lineinfile: dest="{{ nginx_find_result.stdout }}"
              line="include {{ adminrouter_ssl_config_file }};"
              insertbefore="server {"
  notify:
    - dcos-adminrouter reload

