---
- name: run seed job
  shell: docker -H tcp://127.0.0.1:4243 exec -i jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s https://localhost:8443/ -noCertificateCheck -i /var/jenkins_home/.ssh/id_rsa build seed_job
