---
jenkins_port: "8083"
application_name: "jenkins-{{jenkins_user_name}}"
persistent_store: "/mnt/jenkins/{{application_name}}"
jenkins_cli_jar: "/var/jenkins_home/war/WEB-INF/jenkins-cli.jar"
jenkins_cli_groovy: "java -jar {{jenkins_cli_jar}} -noCertificateCheck -s https://localhost:{{jenkins_port}} -i /var/jenkins_home/.ssh/id_rsa groovy ="
