---
- command: mktemp -t "{{application_name}}.XXXXXXXXXX"
  register: mktemp

- name: create setpassword groovy file
  template: src=setpassword.groovy.j2 dest={{mktemp.stdout}}

- name: run setpassword
  shell: cat {{mktemp.stdout}} | docker {{docker_options}} exec -i {{runningjenkins}} sh -c '{{jenkins_cli_groovy}}'

- file: path={{mktemp.stdout}} state=absent
