---
# Cleans up customer related artifacts from the Docker Registry (Quay). Expects the following
# data structure:
#
#  quay:
#    user: "some_user"   # name of the customer user
#    team: "test"        # name of the customer team ( >4 and <=10 chars)
#    org: "test"         # name of customer org.
#
- name: "Deleting quay test repository 'hello_world' for org '{{quay.org}}'..."
  uri:
    url: "{{quay_registry_host}}/api/v1/repository/{{quay.org}}/hello_world"
    method: DELETE
    body_format: json
    validate_certs: no
    status_code: "204,400,403"
    headers:
      Authorization: "Bearer {{quay_oauth_token}}"
      Accept: application/json
      Content-Type: application/json
    return_content: no

- name: delete customer robot
  uri:
    url: "{{ quay_registry_host }}/api/v1/organization/{{ quay.org }}/robots/robotti"
    method: DELETE
    validate_certs: no
    status_code: "204,400,403"
    headers:
      Authorization: "Bearer {{quay_oauth_token}}"
      Accept: application/json
      Content-Type: application/json
    return_content: no
  no_log: true

- name: "Deleting quay team '{{quay.team}}' for org '{{quay.org}}'..."
  uri:
    url: "{{quay_registry_host}}/api/v1/organization/{{quay.org}}/team/{{quay.team}}"
    method: DELETE
    body_format: json
    validate_certs: no
    status_code: "204,400,403"
    headers:
      Authorization: "Bearer {{quay_oauth_token}}"
      Accept: application/json
      Content-Type: application/json
    return_content: no
  no_log: true

- name: "Deleting quay user '{{quay.user}}' from team 'owners' for org '{{quay.org}}'..."
  uri:
    url: "{{quay_registry_host}}/api/v1/organization/{{quay.org}}/team/owners/members/{{quay.user}}"
    method: DELETE
    body_format: json
    validate_certs: no
    status_code: "204,400,403"
    headers:
      Authorization: "Bearer {{quay_oauth_token}}"
      Accept: application/json
      Content-Type: application/json
    return_content: no
  no_log: true

- name: "Deleting quay org '{{quay.org}}'..."
  uri:
    url: "{{quay_registry_host}}/api/v1/superuser/organizations/{{quay.org}}"
    method: DELETE
    body_format: json
    validate_certs: no
    status_code: "204,400,403"
    headers:
      Authorization: "Bearer {{quay_oauth_token}}"
      Accept: application/json
      Content-Type: application/json
    return_content: no
  no_log: true

- name: "Deleting quay user '{{quay.user}}'..."
  uri:
    url: "{{quay_registry_host}}/api/v1/superuser/users/{{quay.user}}"
    method: DELETE
    body_format: json
    validate_certs: no
    status_code: "204,400,404"
    headers:
      Authorization: "Bearer {{quay_oauth_token}}"
      Accept: application/json
      Content-Type: application/json
    return_content: no