---
- name: Delete OpenStack ports between subnets
  os_port:
    state: absent
    name: "{{ item.0.name }}_{{ item.1.subnet }}_port"
    network: "{{ item.0.name }}"
  with_subelements: 
    - openstack_interfaces
    - routes 

