---
#-- Playbook for building mesos-master instances
- hosts: mesos-bootstrap
  remote_user: "{{ remote_user }}"

- hosts: mesos-master
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: root
  serial: "{{ batch_size | default(1) }}"
  roles:
  - deploy/audit
  - filesystem
  - mesos/common
  - mesos/master
  - mesos/marathon
  - role: dns/record
    domain_name: mesos-{{ region }}
