---
#-- Master playbook to run all grafana monitoring playbooks

- include: avi/monitoring.yml
- include: elasticsearch-proxy/monitoring.yml
- include: graphite/carbon/monitoring.yml
- include: mesos/marathon/monitoring.yml
- include: mesos/monitoring.yml
- include: metronome/monitoring.yml
- include: vault/monitoring.yml
