---
- hosts: admin-proxy
  become: yes
  become_user: root
  vars:
    haproxy_services:
      - name: ha-grafana
        virtual_ip: 192.168.1.129
        port: 443
        mode: tcp
        hostgroup: graphite
        balance: roundrobin
  roles:
    - haproxy
