---
- hosts: "{{ hostgroup | default('all') }}:!localhost"
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: root
  tasks:
  - debug: msg="{{ ansible_hostname }} public[{{ openstack['public_v4'] }}] private[{{ openstack['private_v4'] }}]"

- include: ./vault/test.yml
