---
quay_registry_host: "https://{{docker_registry}}"
quay_oauth_token: "{{lookup('vault', '{{vault_environment}}', 'quay_api_oauth_token')}}"
cred_dir: "/etc/dockercreds"
robot_cred_dir: "{{ customer.shortname }}+robotti"
quay:
  org: "{{customer.shortname}}"
