---
- name: Install uwsgi init.d script
  template: src=redhat_uwsgi_service.j2 dest=/etc/init.d/uwsgi
  notify: restart uwsgi

- name: Check the install scripts perms
  file: path=/etc/init.d/{{ item }} mode=0755 owner=root group=root
  with_items:
    - carbon-cache
    - uwsgi
