---
- hosts: localhost
  vars_files:
      - "{{base_dir}}/playbooks/customer/vars/{{customer_name}}.yml"
  roles:
    - role: jenkins/customer/cleanup

- hosts: mesos-agent
  run_once: True
  become: yes
  tasks:
    - file: path=/mnt/jenkins/jenkins-{{customer_name}} state=absent
