---
- name: install carbonate package dependencies
  package: name={{ item }} state=installed
  with_items:
    - gcc
    - python-devel
    - at

- name: install carbonate
  pip: name=carbonate

- name: Start and enable atd
  service: name=atd enabled=yes state=started

- name: update carbon user
  user:
    name: carbon
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/bash
  register: carbon_user

- name: allow access across carbonate accounts
  authorized_key:
    user: carbon
    key: "{{ item }}"
  with_items: "{{ groups['carbon-cache'] | map('extract', hostvars, 'carbon_user') | map(attribute='ssh_public_key') | list }}"

- name: configure carbonate
  template: src=carbonate.conf.j2 dest=/opt/graphite/conf/carbonate.conf

- name: carbonate run dir
  file: path=/var/run/carbonate state=directory owner=carbon group=carbon mode=0750
