---
- name: restart running jenkins
  shell: docker -H tcp://127.0.0.1:4243 exec -i jenkins java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s https://localhost:8443/ -noCertificateCheck -i /var/jenkins_home/.ssh/id_rsa safe-restart

- name: wait for jenkins to be ready
  uri:
    url: https://127.0.0.1
    status_code: 403
    validate_certs: no
  register: jenkins_result
  until: jenkins_result.status == 403
  retries: 60
  delay: 3
