---
- command: mktemp -t "{{application_name}}.XXXXXXXXXX"
  register: mktemp

- name: create credentials file
  template: src=cust_credentials.groovy.j2 dest={{mktemp.stdout}}

- name: add customer credentials
  shell: cat {{mktemp.stdout}} | docker exec -i {{runningjenkins}} sh -c '{{jenkins_cli_groovy}}'

- file: path={{mktemp.stdout}} state=absent

- file: path={{persistent_store}}/secrets/initialAdminPassword state=absent
