- hosts: worker-1-*
  become: yes
  roles:
    - role: quay/clair/postgres/setup
    
- hosts: worker
  become: yes
  roles:
    - role: dns/record
      domain_name: scanner-{{region}}
    - docker/login
    - quay/clair/scanner/setup
