---
#-- Install statsd

#-- Dependencies
- name: StatsD package dependencies
  package: name={{ item }} state=present
  with_items:
    - nodejs
    - git

- name: Create node user
  user: name=node state=present shell=/bin/false system=yes

- name: Create log directory
  file: path=/var/log/statsd owner=node group=node state=directory

- name: Install statsd from GitHub
  git: "repo=https://github.com/etsy/statsd.git dest=/opt/statsd update=no"

- name: Get directory permissions
  stat: path=/opt/statsd
  register: permissions

- name: Set file permissions
  file: path=/opt/statsd state=directory recurse=yes owner=node group=node
  when: permissions.stat.pw_name != 'node'

- name: Create statsd config file
  template: src=statsd_config.js.j2 dest=/opt/statsd/server_config.js owner=node group=node

- name: Create systemd unit file
  template: src=statsd.service.j2 dest=/etc/systemd/system/statsd.service owner=root group=root

- name: Enable statsd
  service: name=statsd enabled=yes

- name: Start statsd
  service: name=statsd state=started
