---
- hosts: carbon-relay
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: root
  vars:
   - graphite_role: frontend
  roles:
  - role: deploy/audit
  - role: filesystem
  - role: collectd
  - role: graphite-collectd
  - role: graphite/carbon-c-relay
